### ISSUE TITLE
Add CIDR/ASN/IP's file support

### ISSUE THREAD

**Issue by NagliNagli** [resyncgg/armada#1]
Hi,

Would be cool to supply a file with many CIDR's/IP's/ASN's, instead of going for each in the targets file

Thanks alot!

**Comment by d0nutptr** [comment]
Hey thanks for the suggestion!

It's a feature I'll consider adding soon since it should be relatively simple. In the meantime, you can currently specify multiple CIDRs/IPs using a comma like so:

```
armada 1.2.3.0/24,8.8.8.8 -p 53,80,443,1000-1100
```

**Comment by d0nutptr** [comment]
Hey @NagliNagli ! I've updated Armada to 1.1.1 which now supports passing targets via a file. 

You can update armada to get this new functionality by running 

```
cargo install armada
```

And don't forget to give the binary `CAP_NET_RAW` if this is how you choose to use armada.

```
sudo setcap 'cap_net_raw+ep' $(which armada)
```

## Supported methods to supply targets

1. `--targets` (`-t`)
```
armada -t 1.1.1.1 -p 80,443
```
   
2. `--target_file`
```
armada --target_file ips_and_cidrs.txt -p 80,443
```
    
3. stdin
```
cat ips_and_cidrs.txt | armada -p 80,443
```
