### ISSUE TITLE
-t flag causes a panic bug when you add a txt list to it

### ISSUE THREAD

**Issue by falcantaralinode** [resyncgg/armada#12]
On Armada 1.1.2, whenever I run `armada -t ips.txt -p 1-65535` I get this error: 

```
$  armada -t ips.txt -p 1-65535
thread 'main' panicked at 'Unable to parse target 'ips.txt'.: IncorrectIpCIDRString', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/armada-1.1.2/src/args.rs:93:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

However when I run `armada --target_file ips.txt -p 1-65535` it worked as intended. If that is the intention then it might be worth revising the docs or changing the functionality to be that `-t` targets ips and files

**Comment by d0nutptr** [comment]
I think you might have read the documentation incorrectly.

Both the command line help information and the documentation correctly note that `-t` is for passing ip/cidr information via command line (it is an alias for `--targets`), and not a filename. If you want to pass a file, you should use `--target_file` as you have above.  

From the CLI help (`-h`):

```
  -t, --targets <targets>...
            The IP and CIDR ranges to scan.

        --target_file <target_file>
            A newline delimited file containing IP addresses and CIDR ranges to scan.
```

From the readme:
> Via command-line argument
> `armada -t 1.2.3.4,8.8.8.0/24 -p 1-1000`

> A newline delimited targets file
> `armada --target_file some_ips_and_cidrs.txt -p 1-1000`

**Comment by falcantaralinode** [comment]
You could add `-tf` for target file if it doesn't interfere with anything else.
