### ISSUE TITLE
RUST_BACKTRACE=1 problem

### ISSUE THREAD

**Issue by kacakb** [resyncgg/armada#13]
i run this command :sudo armada --target_file sortip -p 1-444

but output is:

thread 'main' panicked at 'Unable to parse target ''.: IncorrectIpCIDRString', /home/k/.cargo/registry/src/github.com-1ecc6299db9ec823/armada-1.1.2/src/args.rs:93:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by d0nutptr** [comment]
Do you have a sample from that sortip file? I suspect it's formatted in a way that is breaking the file parsing

**Comment by kacakb** [comment]
in this format:

1.1.x.x
1.2.x.x
1.3.x.x
1.4.x.x
1.5.x.x
1.6.x.x
1.7.x.x
..
..

**Comment by d0nutptr** [comment]
Can you pipe that into `xxd` and show the output? Something appears to be off about your file. I just ran a similar test and it worked fine.

(what I had)
```
d0nut@bakery:~/src/sandbox$ cat ips.txt 
1.1.1.1
1.2.3.4
8.8.8.8
d0nut@bakery:~/src/sandbox$ cat ips.txt | armada -p 80,443
1.1.1.1:80
1.1.1.1:443
8.8.8.8:443
```

This is what I have when I pipe out to xxd

```
d0nut@bakery:~/src/sandbox$ cat ips.txt | xxd
00000000: 312e 312e 312e 310a 312e 322e 332e 340a  1.1.1.1.1.2.3.4.
00000010: 382e 382e 382e 380a                      8.8.8.8.
```

(delimited with `0x0a`)

**Comment by d0nutptr** [comment]
Nothing? I'll close as unreproducible this weekend if not

**Comment by kacakb** [comment]
There was a blank space in my word list. I fixed it and it was fixed

**Comment by d0nutptr** [comment]
No worries! Sorry I took so long to get back to this xD I'll close this now
