### ISSUE TITLE
setting rate limit lower than 10 stuck forever

### ISSUE THREAD

**Issue by AaronChen0** [resyncgg/armada#6]
Failed examples:
armada 74.125.130.147 --top100 --rate-limit 2
armada 58.250.137.36 --top100 --rate-limit 9

Working examples:
armada 74.125.130.147 --top100 --rate-limit 10
armada 58.250.137.36 --top100 --rate-limit 11

~# armada --version
armada 1.0.2

**Comment by d0nutptr** [comment]
Ahh yes so I'm aware of this behavior but didn't really expect anyone to want a rate-limit lower than 10 to be used. 

Can you explain your use-case for wanting to run it that slowly?

**Comment by AaronChen0** [comment]
Actually, I don't have to run it that slow. Sometimes, testing armada against specific sites for top100 ports, you have to set the rate limit lower and lower to avoid false negative. But I haven't encounter a site that would require to be that slow. Setting as low as 500 would be enough for most cases. It would be better to document this behavior, saying --rate-limit should be no smaller than 10.

**Comment by d0nutptr** [comment]
Sounds good. What do you think about silently capping the minimum to 10. I can note something about this in the readme.

**Comment by AaronChen0** [comment]
Agree.

**Comment by d0nutptr** [comment]
This was resolved by the aforementioned PR
