### ISSUE TITLE
armada not installing

### ISSUE THREAD

**Issue by ashutoshsharma84** [resyncgg/armada#7]
unable to install armada, getting below error.
![armada](https://user-images.githubusercontent.com/50571561/123777444-d659f300-d8ed-11eb-9c08-317a9153b249.png)

**Comment by d0nutptr** [comment]
Heyo! I think you either:

* Have an out-of-date version of rust

or 

* Installed cargo via `apt-get`

I would recommend installing rust using the instructions in the README to avoid this problem. Let me know if that helps!

**Comment by ashutoshsharma84** [comment]
Hi,
Thanks for the reply, the issue is resolved.
Steps:
1) Removed all rust packages in the system
2) Installed as per the instruction provided in the README section. 
3)Able to run armada

Another Issue:-
1)
While scanning all ports. no result is found.
![armada1](https://user-images.githubusercontent.com/50571561/123932074-b6d6cf00-d9ae-11eb-99f8-a429a4fbc57e.png)

But when scanning with "--top100" option, some ports is showing open. Why is the result different??.
I have checked the ranges.rs file where ports found are mentioned in the list.
![armada2](https://user-images.githubusercontent.com/50571561/123932698-4ed4b880-d9af-11eb-810a-65cc64a6dab9.png)

2)
While scanning an IP first time, armada is not detecting all open ports. When scanned for second or third time, more open ports are showing.
![armada3](https://user-images.githubusercontent.com/50571561/123933776-52b50a80-d9b0-11eb-88e7-33d85a857b6e.png)


Thanks for the support :)

**Comment by d0nutptr** [comment]
Glad to hear it works for you now!

i suspect your (new) problem is that armada’s default speed is too fast for your home internet. I recommend running armada from a VPS where you would likely have a better internet connection (not in terms of bandwidth, but reliability, packets-per-second, and for CIDR ranges, the routing capacity.

You can try to use the —rate-limit flag and set a lower value to see if that helps. For example, start with 500 or 1000 and see if that improves your discovery.

An additional factor could be that the remote target is blocking port scanning after too many ports (why top 1000 might work but the full 65535 wont)

**Comment by ashutoshsharma84** [comment]
Thanks,
I also thought of using "--rate-limit" for seeing the result.
