### ISSUE TITLE
Add File as an Input

### ISSUE THREAD

**Issue by freddyal0x01** [resyncgg/armada#8]
Great tool, however the one feature that I would like to have is the ability to feed the tool a file list of ips so I can scan multiple ips at once.

**Comment by d0nutptr** [comment]
Hello @freddyal0x01 !

Thanks for the request :) 

Let me add that for you tonight!

**Comment by d0nutptr** [comment]
Hello! Thanks for the issue :) I've updated Armada to 1.1.1 which now supports this. You can update armada by 

```
cargo install armada
```

And don't forget to give the binary `CAP_NET_RAW` if this is how you choose to use armada.

```
sudo setcap 'cap_net_raw+ep' $(which armada)
```

## Supported methods to supply targets

1. `--targets` (`-t`)
```
armada -t 1.1.1.1 -p 80,443
```
   
2. `--target_file`
```
armada --target_file ips_and_cidrs.txt -p 80,443
```
    
3. stdin
```
cat ips_and_cidrs.txt | armada -p 80,443
```
